### ISSUE TITLE
Specifications: missing `version` as a concrete property

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-3gpp#14]
Each 3GPP ID has a version, e.g. `0.5.0` in `3GPP TR 36.860-13:Rel-13/0.5.0`.

Yet, the `0.5.0` part is not captured anywhere in Relaton data. Could it be in a `version`, `edition` or something like that?

**Comment by ronaldtse** [comment]
According to the official 3GPP metadata, this is the "version":
https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=2564

<img width="673" alt="Screen Shot 2022-08-04 at 4 06 52 PM" src="https://user-images.githubusercontent.com/11865/182796736-2e5cf3cf-7e1e-471f-b28c-b76fcf30b3d9.png">

So we should map this value into `version`.

**Comment by ronaldtse** [comment]
i.e. `0.5.0` should appear as the `version` number.

**Comment by andrew2net** [comment]
Fixed in v1.19.2
