### ISSUE TITLE
rapporteurId is not a document identifier

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-3gpp#5]
From: https://github.com/ietf-ribose/relaton-data-3gpp/issues/4

@strogonoff :
> Is this an actual document type, like DOI or IEEE?

No. This is wrong. `rapporteurId` is not a Document Identifier, it is the 3GPP internal ID of the "Rapporteur" of the document (a person).

**Comment by ronaldtse** [comment]
Maybe this should go into editorial group information? (https://github.com/ietf-ribose/relaton-data-3gpp/issues/5#issuecomment-996381956)

**Comment by andrew2net** [comment]
@ronaldtse all `rapporteurId` are integer numbers. I don't think it bears any information to relaton users. Maybe there is a relation to rapporteurs names?

**Comment by ronaldtse** [comment]
Yes they are related to the names of rapporteurs. Is there a table for rapporteurs?

In any case they are not document identifiers and we should remove from docidentifier

**Comment by andrew2net** [comment]
@ronaldtse  I found only "2003-02-06_spec_level01_table" which has relation with "Specs_GSM+3G" and filed `Rapporteur`. For example the row form "Specs_GSM+3G":
```ruby
{:Type=>"TR",
 :Number=>"00.01U"
...
```
has related row in the "2003-02-06_spec_level01_table":
```ruby
{:Type=>"TR",
 :Number=>"00.01U",
 :Title=>"Work programme for the standarization of Universal Mobile Telecommunications System (UMTS)",
 :WG=>"-",
 :Rapporteur=>"RAPELI, Juha",
 :general_remarks=>nil,
 :G=>nil,
 :U=>"U",
 :"Spec withdrawn"=>"spec withdrawn",
 :Directory=>"#http://www.3gpp.org/ftp/Specs/archive/00_series/00.01U/#"}
```
which has `:Rapporteur=>"RAPELI, Juha"` field. Would it be correct if we add "RAPELI, Juha" to editorial groups?

**Comment by ronaldtse** [comment]
Actually the `temp_status` table provides up-to-date information (latest update Oct 2021) regarding:
* rapporteur
* rapporteur organization
* freeze meeting
* WG prime / WG other

<img width="1567" alt="Screenshot 2021-12-21 at 12 33 08 PM" src="https://user-images.githubusercontent.com/11865/146871505-26299d5a-a31d-483d-be70-9586aa24d084.png">

Let's use this.

**Comment by andrew2net** [comment]
> Maybe this should go into editorial group information? ([ietf-ribose/relaton-data-3gpp#5 (comment)](https://github.com/ietf-ribose/relaton-data-3gpp/issues/5#issuecomment-996381956))

@ronaldtse maybe rapporteur should go into contributor?

**Comment by ronaldtse** [comment]
Excellent idea @andrew2net .
