### ISSUE TITLE
Fix parsing of "editorial group"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-3gpp#6]
From: https://github.com/ietf-ribose/relaton-data-3gpp/issues/5

@strogonoff:

------

- `editorialgroup` seems like some custom extension outside of Relaton core but relevant for some citations?
- The dash in the following example makes `editorialgroup` contents seem ill-parsed, example:

        "editorialgroup": [
            {
                "name": "C1",
                "type": "prime"
            },
            {
                "name": "-",
                "type": "other"
            },
            {
                "name": "T2",
                "type": "former"
            }
        ],

Example items:

- https://demo.bibxml.org/api/v1/ref/3gpp/TR_33.879_REL-13_0.1.0/
- https://demo.bibxml.org/api/v1/ref/3gpp/TS_29.163_REL-9_9.21.0/
- https://demo.bibxml.org/api/v1/ref/3gpp/TS_27.007_REL-15_15.3.0/ (extended “release” value)

--------

This is actually the `meeting` ID from the database, it is not **THE editorial group** itself, but it is editorial group information. It shouldn't be broken down, e.g. "C1-T2" is correct without splitting it.

<img width="170" alt="Screenshot 2021-12-17 at 10 15 40 AM" src="https://user-images.githubusercontent.com/11865/146477824-983d590e-f47f-455e-bf77-f874cbab975e.png">

**Comment by andrew2net** [comment]
@ronaldtse they have already split in DB:
```
{:Type=>"TR",
 :Number=>"33.879",
 :"For publication"=>"0",
 :Title=>"Study on security enhancements for Mission Critical Push To Talk (MCPTT) over LTE",
 :"former WG"=>nil,
 :"WG prime"=>"S3",
 :"WG other"=>nil,
...

{:Type=>"TS",
 :Number=>"29.163",
 :"For publication"=>"1",
 :Title=>"Interworking between the IP Multimedia (IM) Core Network (CN) subsystem and Circuit Switched (CS) networks",
 :"former WG"=>nil,
 :"WG prime"=>"C3",
 :"WG other"=>nil,
...

{:Type=>"TS",
 :Number=>"27.007",
 :"For publication"=>"1",
 :Title=>"AT command set for User Equipment (UE)",
 :"former WG"=>"T2",
 :"WG prime"=>"C1",
 :"WG other"=>"-",
...
```
Sope specs look like this:
```
{:Type=>"TS",
 :Number=>"01.02",
 :"For publication"=>"1",
 :Title=>"General Description of a GSM Public Land Mobile Network (PLMN)",
 :"former WG"=>"SMG01  /  SMG02  /  SMG03",
 :"WG prime"=>"S1",
 :"WG other"=>"GP / CP",
...
```
Therefore we can't just join them, can we?

**Comment by ronaldtse** [comment]
@andrew2net sorry, yes you are right. These WG codes are split as "prime" and "other" components in the `Specs_GSM+3G` table.

It's just so strange the `WG other` can be just `-`...

<img width="1013" alt="Screenshot 2021-12-17 at 10 58 06 PM" src="https://user-images.githubusercontent.com/11865/146563612-bdac268f-e4d5-48ca-8356-eb2a13aa00c6.png">

**Comment by ronaldtse** [comment]
Maybe you should rename them:

```json
  "editorialgroup": [
      {
          "name": "C1",
          "type": "wg-prime"
      },
      {
          "name": "-",
          "type": "wg-other"
      },
      {
          "name": "T2",
          "type": "wg-former"
      }
  ],
```

**Comment by ronaldtse** [comment]
For the content of "former WG" being `S1  /  SMG01  /  T2  /  SMG04`, it should be something like:

```json
"wg-former": [
[
      {
          "name": "S1",
          "type": "wg-prime"
      },
      {
          "name": "SMG01",
          "type": "wg-other"
      }
],
[
      {
          "name": "T2",
          "type": "wg-prime"
      },
      {
          "name": "SMG04",
          "type": "wg-other"
      }
],
]
```

But many of them don't have both components (e.g. `SPAN3  /  N4  /  SMG03?`).

It's too inconsistent, so we might as well not parse "former WG".

**Comment by ronaldtse** [comment]
Maybe `-` just means `NULL` and we just drop that.

**Comment by andrew2net** [comment]
Yes, I think `-` should be dropped. Will do it.
Concerning nested workgroups `"wg-former": [{ "name": "S1", "type": "wg-prime" }]` we don't have such a option in the Relaton model.

**Comment by andrew2net** [comment]
@ronaldtse I've removed workgroups with `-` names. Can we close this issue?

**Comment by ronaldtse** [comment]
Yes, thank you.
