### ISSUE TITLE
URGENT: Missing publication/achieved date

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-3gpp#9]
From https://github.com/ietf-ribose/relaton-data-3gpp/issues/7#issuecomment-1044879983

------

@strogonoff actually there is an error in what I said about "confirmation date". The "confirmation date" is not the "publication date", it is the date that the standard was "confirmed" that it does not need updating, after "publication".

Let's compare these two sources:
* http://xml2rfc.tools.ietf.org/public/rfc/bibxml5/reference.3GPP.01.31.xml
* https://github.com/ietf-ribose/relaton-data-3gpp/blob/main/data/TR_01.31_R98_7.0.1.yaml

First source:
```xml
<reference anchor="3GPP.01.31">
<front>
<title>
Fraud Information Gathering System (FIGS); Service requirements; Stage 0
</title>
<author>
<organization>3GPP</organization>
</author>
<date day="26" month="June" year="1998"/>
</front>
<seriesInfo name="3GPP TR" value="01.31 7.0.1"/>
<format type="HTML" target="http://www.3gpp.org/ftp/Specs/html-info/0131.htm"/>
</reference>
```

In the new data (latter source), the only date provided is the "confirmation date":
https://github.com/ietf-ribose/relaton-data-3gpp/blob/9ff6ccb22ae83ed71705dadebe770cecbb121413/data/TR_01.31_R98_7.0.1.yaml#L18-L19

However, the source data provides these dates too:
<img width="1141" alt="Screenshot 2022-02-19 at 1 25 41 AM" src="https://user-images.githubusercontent.com/11865/154732298-7a81a38b-d19e-4218-b72e-e5de64e0dafe.png">
<img width="1140" alt="Screenshot 2022-02-19 at 1 25 52 AM" src="https://user-images.githubusercontent.com/11865/154732314-b9f81fbb-ea77-472f-920b-1d2585599ff8.png">

Here the "ACHIEVED DATE" is clearly the "publication date".

**Comment by andrew2net** [comment]
@ronaldtse which table has the "ACHIEVED DATE" field?

**Comment by ronaldtse** [comment]
@andrew2net `2001-04-25_schedule` is the table.
